import { contextBridge, ipcRenderer } from 'electron'
import type { AppApi } from '../shared/api'

const api: AppApi = {
  previewLayoutPdf: (input) => ipcRenderer.invoke('layout:pdf-preview', input),
  previewSummaryPdf: (input) => ipcRenderer.invoke('summary:pdf-preview', input),
  previewEstimatePdf: (input) => ipcRenderer.invoke('estimate:pdf-preview', input),
  saveEstimateXlsx: (input) => ipcRenderer.invoke('estimate:xlsx-save', input),
  savePdfPreview: (token) => ipcRenderer.invoke('pdf:save', token),
  closePdfPreview: (token) => ipcRenderer.invoke('pdf:close', token),
  readCompany: () => ipcRenderer.invoke('company:read'),
  saveCompany: (input) => ipcRenderer.invoke('company:save', input),
  addCatalogOption: (input) => ipcRenderer.invoke('catalog:add-option', input),
  createEstimate: (input) => ipcRenderer.invoke('estimate:create', input),
  readEstimate: (input) => ipcRenderer.invoke('estimate:read', input),
  saveEstimate: (input) => ipcRenderer.invoke('estimate:save', input),
  listEstimates: (input) => ipcRenderer.invoke('estimate:list', input),
  editSummary: (input) => ipcRenderer.invoke('summary:edit', input),
  readSummary: (input) => ipcRenderer.invoke('summary:read', input),
  exportSummary: (input) => ipcRenderer.invoke('summary:export', input),
  readLayout: (id) => ipcRenderer.invoke('layout:read', id),
  saveLayout: (input) => ipcRenderer.invoke('layout:save', input),
  readMaterials: (id) => ipcRenderer.invoke('materials:read', id),
  changeMaterials: (input) => ipcRenderer.invoke('materials:change', input),
  readTakeoff: (address) => ipcRenderer.invoke('takeoff:read', address),
  previewTakeoff: (input) => ipcRenderer.invoke('takeoff:preview', input),
  applyTakeoff: (input) => ipcRenderer.invoke('takeoff:apply', input),
  workspace: () => ipcRenderer.invoke('workspace:read'),
  saveSelection: (value) => ipcRenderer.invoke('selection:save', value),
  createClient: (name) => ipcRenderer.invoke('client:create', name),
  renameClient: (id, name) => ipcRenderer.invoke('client:rename', id, name),
  deleteClient: (id) => ipcRenderer.invoke('client:delete', id),
  createProject: (input) => ipcRenderer.invoke('project:create', input),
  updateProject: (id, input) => ipcRenderer.invoke('project:update', id, input),
  deleteProject: (id) => ipcRenderer.invoke('project:delete', id),
  importPdfs: (projectId) => ipcRenderer.invoke('drawing:import', projectId),
  readPdf: (id) => ipcRenderer.invoke('drawing:read', id),
  renameDrawing: (id, name) => ipcRenderer.invoke('drawing:rename', id, name),
  deleteDrawing: (id) => ipcRenderer.invoke('drawing:delete', id),
  createBackup: () => ipcRenderer.invoke('backup:create'),
  restoreBackup: () => ipcRenderer.invoke('backup:restore'),
  openDataFolder: () => ipcRenderer.invoke('data:open')
}
contextBridge.exposeInMainWorld('sekisan', Object.freeze(api))
