import { expect } from '@playwright/test'
import assert from 'node:assert/strict'
export async function exerciseEstimate(page) {
  const original = await page.evaluate(async () => {
    const w = await window.sekisan.workspace()
    const r = await window.sekisan.readTakeoff({ drawingId: w.data.drawings[0].id, pageNumber: 1 })
    return r.data
  })
  await page.getByRole('button', { name: '数量集計', exact: true }).click()
  await expect(page.locator('.summary-page')).toHaveAttribute('aria-busy', 'false')
  await page.getByLabel('集計する部位').selectOption('floor')
  await expect(page.getByTestId('summary-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'この集計から見積を作成', exact: true }).click()
  await expect(page.getByLabel('見積名', { exact: true })).toHaveValue('本社ビル 3階 内装改修工事')
  await expect(page.getByTestId('estimate-row')).toHaveCount(1)
  await expect(page.getByLabel('見積の発行者', { exact: true })).toHaveValue(
    '自社情報テスト株式会社\n〒100-0001\n東京都千代田区\nTEL 03-0000-0000'
  )
  await expect(page.getByLabel('見積の取引条件', { exact: true })).toHaveValue(
    '有効期限：発行日から30日間\n支払条件：月末締め・翌月末払い\n工事日程は別途協議'
  )
  await expect(page.getByText(/消費税|税込/)).toHaveCount(0)
  await expect(page.locator('.estimate-table th').nth(4)).toHaveText('仕様・規格')
  await expect(page.locator('.estimate-table th').nth(0)).toHaveText('大項目（工事区分）')
  await expect(page.locator('.estimate-table th').nth(1)).toHaveText('部屋')
  await expect(
    page.getByRole('button', { name: '明細1の大項目を上と同じにする', exact: true })
  ).toBeDisabled()
  await expect(page.getByLabel('明細1の数量', { exact: true })).toHaveValue('15.0')
  await expect(page.getByTestId('estimate-total')).toHaveText('67,500 円')
  await page.getByLabel('見積名', { exact: true }).fill('本社ビル 御見積書')
  await page.getByLabel('見積の発行者', { exact: true }).fill('東京カーペット株式会社\n営業部')
  await page.getByLabel('見積の取引条件', { exact: true }).fill('有効期限：発行から30日')
  await page.getByLabel('見積の納期', { exact: true }).fill('9月末・別途打合せ')
  await page.getByLabel('明細1の備考', { exact: true }).fill('新規ボード下地として')
  await page.getByLabel('明細1の工事区分', { exact: true }).fill('販売センター内装仕上工事')
  await page.getByLabel('明細1の数量', { exact: true }).fill('12.34')
  await page.getByLabel('明細1の単価', { exact: true }).fill('2000')
  await expect(page.getByLabel('明細1の数量', { exact: true })).toHaveValue('12.3')
  await expect(page.getByTestId('estimate-total')).toHaveText('24,600 円')
  await page.getByRole('button', { name: '明細を追加', exact: true }).click()
  await expect(page.getByLabel('明細2の工事区分', { exact: true })).toHaveValue(
    '販売センター内装仕上工事'
  )
  await expect(
    page.locator('#estimate-section-options option[value="販売センター内装仕上工事"]')
  ).toHaveCount(1)
  await page.getByLabel('明細2の工事区分', { exact: true }).fill('モデルルーム')
  await page.getByRole('button', { name: '明細2の大項目を上と同じにする', exact: true }).click()
  await expect(page.getByLabel('明細2の工事区分', { exact: true })).toHaveValue(
    '販売センター内装仕上工事'
  )
  await expect(page.getByLabel('明細1の数量', { exact: true })).toHaveValue('12.3')
  const material = page.getByLabel('明細2の名称', { exact: true })
  await material.fill('木製')
  await expect(page.getByRole('option', { name: /木製建具/ })).toHaveCount(2)
  await page.getByRole('option', { name: /木製建具.*W900/ }).click()
  await expect(page.getByLabel('明細2の部位', { exact: true })).toHaveValue('建具')
  await expect(page.getByLabel('明細2の単位', { exact: true })).toHaveValue('枚')
  await expect(page.getByLabel('明細2の仕様・規格', { exact: true })).toHaveValue(
    'W900×H2100 ／ 厚み 35 mm'
  )
  await expect(page.getByLabel('明細2の単価', { exact: true })).toHaveValue('12000')
  const nameCell = page.getByTestId('estimate-row').nth(1).locator('td').nth(3)
  await expect(nameCell.locator('input')).toHaveCount(1)
  await expect(nameCell.locator('select')).toHaveCount(0)
  await material.fill('自由入力の仕上げ材')
  await expect(
    page.getByText('一致する材料はありません。そのまま自由入力できます。', { exact: true })
  ).toBeVisible()
  await expect(page.getByLabel('明細2の単価', { exact: true })).toHaveValue('12000')
  await material.press('Escape')
  await expect(material).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: '明細2の名称のマスタを開く', exact: true }).click()
  await expect(page.getByRole('option', { name: /木製建具/ })).toHaveCount(2)
  await page.screenshot({ path: 'test-results/20-material-options.png', fullPage: true })
  await material.fill('W900')
  await material.press('ArrowDown')
  await material.press('Enter')
  await expect(material).toHaveValue('木製建具')
  await expect(material).toHaveAttribute('aria-expanded', 'false')
  await page.screenshot({ path: 'test-results/19-estimate-specification.png', fullPage: true })
  await page.getByLabel('明細2の名称', { exact: true }).fill('諸経費')
  await page.getByLabel('明細2の工事区分', { exact: true }).fill('諸経費')
  await page.getByLabel('明細2の備考', { exact: true }).fill('運搬・搬入を含む')
  await page.getByLabel('明細2の単価', { exact: true }).fill('')
  await page.getByLabel('明細2の仕様・規格', { exact: true }).fill('現場管理費')
  await page.getByLabel('明細2の単位', { exact: true }).selectOption('式')
  await expect(page.getByTestId('estimate-total')).toHaveText('未確定')
  await page.getByLabel('明細2の単価', { exact: true }).fill('1000')
  await expect(page.getByTestId('estimate-total')).toHaveText('25,600 円')
  await page.getByRole('button', { name: '諸経費を追加', exact: true }).click()
  await expect(page.getByLabel('明細3の名称', { exact: true })).toHaveValue('運搬・搬入費')
  await expect(page.getByLabel('明細3の工事区分', { exact: true })).toHaveValue('諸経費')
  await expect(page.getByLabel('明細3の単位', { exact: true })).toHaveValue('式')
  await page.getByLabel('明細3の名称', { exact: true }).fill('削除確認用')
  await page.getByRole('button', { name: '明細3を削除', exact: true }).click()
  await expect(
    page.getByRole('heading', { name: '見積明細を削除しますか？', exact: true })
  ).toBeVisible()
  await expect(page.locator('dialog')).toContainText('削除確認用')
  await page.getByRole('button', { name: 'キャンセル', exact: true }).click()
  await expect(page.getByTestId('estimate-row')).toHaveCount(3)
  await page.getByRole('button', { name: '明細3を削除', exact: true }).click()
  await page.screenshot({ path: 'test-results/22-estimate-delete-confirm.png' })
  await page.getByRole('button', { name: 'この明細を削除', exact: true }).click()
  await expect(page.getByTestId('estimate-row')).toHaveCount(2)
  await expect(page.getByTestId('estimate-total')).toHaveText('25,600 円')
  await page.getByRole('button', { name: '明細2を上へ', exact: true }).click()
  await expect(page.getByLabel('明細1の名称', { exact: true })).toHaveValue('諸経費')
  await page.getByRole('button', { name: '明細1を下へ', exact: true }).click()
  await page.getByRole('button', { name: '見積一覧へ戻る', exact: true }).click()
  await expect(
    page.getByRole('heading', { name: '未保存の変更があります', exact: true })
  ).toBeVisible()
  await page.getByRole('button', { name: '編集を続ける', exact: true }).click()
  await page.getByRole('button', { name: '見積を保存', exact: true }).click()
  await expect(page.getByText('第2版として保存しました。', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/15-estimate.png', fullPage: true })
  await page.getByRole('button', { name: '作成元を確認', exact: true }).click()
  await expect(page.getByRole('heading', { name: '見積の作成元', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '閉じる', exact: true }).click()
  await page.getByLabel('見積の保存履歴', { exact: true }).selectOption('1')
  await expect(page.getByLabel('見積名', { exact: true })).toHaveValue('本社ビル 3階 内装改修工事')
  await expect(page.getByLabel('明細1の単価', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('明細1の備考', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('明細1の備考', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('見積の納期', { exact: true })).toHaveValue('')
  await expect(page.getByTestId('estimate-total')).toHaveText('67,500 円')
  await page.getByLabel('見積の保存履歴', { exact: true }).selectOption('2')
  await expect(page.getByTestId('estimate-total')).toHaveText('25,600 円')
  await page.getByLabel('見積の備考', { exact: true }).fill('保存せず破棄する')
  await page.getByRole('button', { name: '見積一覧へ戻る', exact: true }).click()
  await page.getByRole('button', { name: '破棄して移動', exact: true }).click()
  await expect(page.locator('.estimate-card')).toHaveCount(1)
  await expect(page.locator('.estimate-card')).toContainText('25,600円')
  await page.screenshot({ path: 'test-results/16-estimates.png' })
  await page.getByRole('button', { name: '案件へ戻る', exact: true }).click()
  const after = await page.evaluate(async () => {
    const w = await window.sekisan.workspace()
    const r = await window.sekisan.readTakeoff({ drawingId: w.data.drawings[0].id, pageNumber: 1 })
    return r.data
  })
  assert.deepEqual(after, original)
}
export async function verifySavedEstimate(page) {
  const company = await page.evaluate(() => window.sekisan.readCompany())
  assert.equal(company.data.name, '自社情報テスト株式会社')
  assert.equal(company.data.paymentTerms, '月末締め・翌月末払い')
  await page.getByRole('button', { name: '見積一覧', exact: true }).click()
  await page.locator('.estimate-card').filter({ hasText: '本社ビル 御見積書' }).click()
  await expect(page.getByLabel('見積名', { exact: true })).toHaveValue('本社ビル 御見積書')
  await expect(page.getByTestId('estimate-total')).toHaveText('25,600 円')
  await expect(page.getByLabel('見積の備考', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('明細2の仕様・規格', { exact: true })).toHaveValue('現場管理費')
  await expect(page.getByLabel('見積の納期', { exact: true })).toHaveValue('9月末・別途打合せ')
  await expect(page.getByLabel('明細1の備考', { exact: true })).toHaveValue('新規ボード下地として')
  await expect(page.getByLabel('明細1の工事区分', { exact: true })).toHaveValue(
    '販売センター内装仕上工事'
  )
  await expect(page.getByLabel('見積の保存履歴', { exact: true }).locator('option')).toHaveCount(2)
  await page.getByRole('button', { name: '見積一覧へ戻る', exact: true }).click()
  await page.getByRole('button', { name: '案件へ戻る', exact: true }).click()
}
